const Tool=[
    {
        id:1,
        title:"Apple",
        img:"https://img.icons8.com/ios-filled/512/mac-os.png",
        value:"1",
    },
    {
        id:2,
        title:"Android",
        img:"https://img.icons8.com/glyph-neue/512/android-os.png",
        value:"1",
    },
    {
        id:3,
        title:"Flutter",
        img:"https://img.icons8.com/ios-filled/512/flutter.png",
        value:"1",
    },
    {
        id:4,
        title:"Java",
        img:"https://img.icons8.com/ios-filled/512/java-coffee-cup-logo.png",
        value:"1",
    },
    {
        id:5,
        title:"React Native",
        img:"https://img.icons8.com/ios/512/react-native.png",
        value:"1",
    },
    {
        id:6,
        title:"C#",
        img:"https://img.icons8.com/ios-filled/512/c-sharp-logo.png",
        value:"1",
    },
    {
        id:7,
        title:"C++",
        img:"https://img.icons8.com/ios-filled/512/c-plus-plus-logo.png",
        value:"1",
    },  
    { 
        id:8,
        title:"Swift",
        img:"https://img.icons8.com/ios-filled/512/swift.png",
        value:"1",
    },
    {
        id:9,
        title:"Ionic",
        img:"https://img.icons8.com/ios-filled/512/ionic.png",
        value:"1",
    },
    {
        id:10,
        title:"Kotlin",
        img:"https://img.icons8.com/ios-filled/512/kotlin.png",
        value:"1",
    },
    {
        id:11,
        title:"Augmented Reality",
        img:"https://img.icons8.com/external-outline-lafs/512/external-augmented-reality-distance-education-outline-part-1-outline-lafs.png",
        value:"1",
    },
    {
        id:12,
        title:"Virtual Reality",
        img:"https://img.icons8.com/external-nawicon-glyph-nawicon/512/external-virtual-reality-internet-of-things-nawicon-glyph-nawicon.png",
        value:"1",
    },
]
export default Tool;